const BORDER_INITIAL_OPACITY = 0;
const BORDER_FINAL_OPACITY = 0.1;

const BACKGROUND_INITIAL_COLOR = "#00060C00";
const BACKGROUND_FINAL_COLOR = "#00060CCC";

export const borderOpacityRange = [BORDER_INITIAL_OPACITY, BORDER_FINAL_OPACITY];
export const backgroundRange = [BACKGROUND_INITIAL_COLOR, BACKGROUND_FINAL_COLOR];
